### PR TITLE
add hook_info(otr_status) to export conversation status to infolist

### PR DESCRIPTION
**Pull request by weechatter**
see discussion: https://github.com/glowing-bear/glowing-bear/issues/871

### CODE REVIEW

**Comment by mmb** [comment]
Thanks for the PR @weechatter.

How does this work with multiple conversations if there is only one global variable in the script holding the state?

Can the `otr_info_status_cb` callback be called with arguments that it can use to identify the conversation? Like the way `otr_statusbar_cb` figures it out from the window.

**Comment by mmb** [comment]
It was suggested in IRC to use a buffer local var for this.

@weechatter Are there any downsides to just adding `weechat.buffer_set(buffer, "localvar_set_otr_status", "encrypted")` to `otr_statusbar_cb`?

**Comment by weechatter** [comment]
the status from current buffer will be used. There aren't any downsides using a localvar.
maybe the status from the item should be used, no?

**Comment by fauno** [comment]
hey, i have an implementation of otr status and info for buffer local
vars here, maybe it's useful now:

https://github.com/fauno/weechat-otr/commit/2398d7178602c2ec7fbaa340129c3837db1acf8f

i never made a pr because anything on weechat can change the buffer
local var values, and a malicious script could make other scripts
believe the conversation was secure when it wasn't.

-- 
https://lainventoria.com.ar/

**Comment by mmb** [comment]
@fauno Good point about the buffer vars being changeable by any script. I think this is also true of infos and even the status bar.

I will check and see if there is a more secure way of communicating the status to relays. If there isn't one, buffer local vars sounds like our best bet to me.

**Comment by mmb** [comment]
Added buffer local vars.

**Pull request closed without merging**
